spring:
  application:
    name: user-center
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user_center
    username: root
    password: 123456
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  session:
    timeout: 2592000
server:
  port: 8050
