server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        max-age: 2592000
  address: 0.0.0.0

mybatis-plus:
  configuration:
    # mybatis-plus 自动驼峰转下划线
    map-underscore-to-camel-case: false
  global-config:
    # mybatis-plus 逻辑删除
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1
      logic-not-delete-value: 0
